const fs = require('fs');
const path = require('path');

const packageJSON = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf-8'));

const appJSON = {
    "name": packageJSON.name,
    "version": packageJSON.version,
    "main": packageJSON.main,
    "__note": "This file is generated by scripts/sync-version.js",
};

fs.writeFileSync(path.join(__dirname, '../app/package.json'), JSON.stringify(appJSON), 'utf-8');
console.log('generate app/package.json');
